
name: CookieClicker
version: '3.1.2'
main: eurocity.eu.cookieclickerv3.CookieClickerV3
api-version: '1.20'
commands:
  placeTopRanking:
  cookieclicker:
    description: Öffnet die CookieClicker GUI
    aliases: cookie
