
name: CookieClicker
version: '3.4.1'
main: eurocity.eu.cookieclickerv3.CookieClickerV3
api-version: '1.20'
commands:
  placeTopRanking:
    description: places the top
  cookieclicker:
    description: Opens the CookieClicker GUI
    aliases: cookie
